name: tolymoly
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  dio: ^2.1.16
  timeago: ^2.0.18
  firebase_messaging: ^5.1.5
  oktoast: ^2.1.9
  flutter_facebook_login: ^2.0.1
  # flutter_secure_storage: ^3.2.1+1
  sqflite: ^1.1.6
  intl: ^0.15.8
  multi_image_picker: ^4.5.2
  http_parser: ^3.1.3
  flutter_image_compress: ^0.6.3
  image_cropper: ^1.1.0
  flutter_form_builder: ^3.5.0
  logger: ^0.7.0+2
  # recase: ^2.0.1
  cached_network_image: ^1.1.1
  # carousel_slider: ^1.3.0
  carousel_pro: ^1.0.0
  flutter_account_kit: ^0.7.0
  url_launcher: 5.1.2

  # transparent_image: ^1.0.0
  # easy_localization: ^1.3.1
  zawgyi_converter: ^0.0.4+pre-v0.2
  # shared_preferences: 0.5.3+4
  image_picker: ^0.6.1+4
  webview_flutter: 0.3.14+1
  photo_view: ^0.5.0
  flutter_svg: 0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.3  

flutter_icons:
  image_path: "assets/icons/tolymoly.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/category/
    - assets/tolymoly.db
    - assets/html/

  fonts:
    - family: Unicode
      fonts:
        - asset: assets/fonts/mm3.ttf
    - family: Zawgyi
      fonts:
        - asset: assets/fonts/zawgyi.ttf
      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware.

      # For details regarding adding assets from package dependencies, see
      # https://flutter.dev/assets-and-images/#from-packages

      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware.
      # For details regarding adding assets from package dependencies, see
      # https://flutter.dev/assets-and-images/#from-packages
      # To add custom fonts to your application, add a fonts section here,
      # in this "flutter" section. Each entry in this list should have a
      # "family" key with the font family name, and a "fonts" key with a
      # list giving the asset and other descriptors for the font. For
      # example:
      # fonts:
      #   - family: Schyler
      #     fonts:
      #       - asset: fonts/Schyler-Regular.ttf
      #       - asset: fonts/Schyler-Italic.ttf
      #         style: italic
      #   - family: Trajan Pro
      #     fonts:
      #       - asset: fonts/TrajanPro.ttf
      #       - asset: fonts/TrajanPro_Bold.ttf
      #         weight: 700
      #
      # For details regarding fonts from package dependencies,
      # see https://flutter.dev/custom-fonts/#from-packages
